[package]
name = "tokio-trace-macros"
version = "0.1.0"
authors = ["Eliza Weisman <eliza@buoyant.io>"]

[dependencies]
tokio-trace = "0.1.0"

[dev-dependencies]
tokio-trace-log = { path = "../tokio-trace-log" }
env_logger = "0.5"
