[workspace]

members = [
    "tracing",
    "tracing-core",
    "tracing-attributes",
    "tracing-futures",
    "tracing-tower",
    "tracing-log",
    "tracing-macros",
    "tracing-subscriber",
    "tracing-serde",
    "examples"
]
