[package]
name = "tracing-futures"
version = "0.0.1"
authors = ["Eliza Weisman <eliza@buoyant.io>"]

[features]
default = ["tokio"]

[dependencies]
futures = "0.1"
tracing = { version = "0.1", path = "../tracing" }
tokio = { version = "0.1", optional = true }
tokio-executor = { version = "0.1", optional = true }

[dev-dependencies]
tokio = "0.1.21"
tracing-fmt = { path = "../tracing-fmt" }
tracing-core = { path = "../tracing-core" }
