[package]
name = "tracing-futures"
version = "0.0.1"
authors = ["Eliza Weisman <eliza@buoyant.io>"]
edition = "2018"

[features]
default = ["futures-01", "tokio"]
futures-01 = ["futures"]
std-future = ["pin-utils"]

[dependencies]
futures = { version = "0.1", optional = true }
pin-utils = { version = "0.1.0-alpha.4", optional = true }
tracing = "0.1"
tokio = { version = "0.1", optional = true }
tokio-executor = { version = "0.1", optional = true }

[dev-dependencies]
tokio = "0.1.22"
tokio-test = { git = "https://github.com/tokio-rs/tokio.git" }
tracing-fmt = { path = "../tracing-fmt" }
tracing-core = "0.1.2"
