[package]
name = "tracing-examples"
version = "0.0.0"
publish = false
edition = "2018"

[features]
default = []

[dev-dependencies]

# tracing crates
tracing = { path = "../tracing", version = "0.2"}
tracing-core = { path = "../tracing-core", version = "0.2"}
tracing-error = { path = "../tracing-error" }
tracing-flame = { path = "../tracing-flame" }
tracing-tower = { version = "0.1.0", path = "../tracing-tower" }
tracing-subscriber = { path = "../tracing-subscriber", version = "0.3", features = ["json", "chrono"] }
tracing-futures = { version = "0.3", path = "../tracing-futures", features = ["futures-01"] }
tracing-attributes =  { path = "../tracing-attributes", version = "0.2"}
tracing-log = { path = "../tracing-log", version = "0.2", features = ["env_logger"] }
tracing-serde = { path = "../tracing-serde" }
tracing-opentelemetry = { path = "../tracing-opentelemetry" }
tracing-journald = { path = "../tracing-journald" }

# serde example
serde_json = "1.0"

futures = "0.3"
tokio = { version = "0.2.12", features = ["full"] }

# env-logger example
env_logger = "0.7"

# tower examples
tower = "0.3"
tower-util = "0.3.1"
tower-make = "0.3"
http = "0.2"
hyper = "0.13.2"
rand = "0.7"
bytes = "0.5"
clap = "2.33"

# sloggish example
ansi_term = "0.12"
humantime = "2.0"
log = "0.4"

# infero example
inferno = "0.10.0"
tempdir = "0.3.7"

# opentelemetry example
opentelemetry = { version = "0.8", default-features = false, features = ["trace"] }
opentelemetry-jaeger = "0.7"
