[package]
name = "examples"
version = "0.0.0"
publish = false
edition = "2018"

[features]
default = []

[dev-dependencies]

# tracing crates
tracing = { path = "../tracing", version = "0.1"}
tracing-core = { path = "../tracing-core", version = "0.1"}
tracing-error = { path = "../tracing-error" }
tracing-flame = { path = "../tracing-flame" }
tracing-tower = { version = "0.1.0", path = "../tracing-tower" }
tracing-subscriber = { path = "../tracing-subscriber", version = "0.2.4", features = ["json", "chrono"] }
tracing-futures = { version = "0.2.1", path = "../tracing-futures", features = ["futures-01"] }
tracing-attributes =  { path = "../tracing-attributes", version = "0.1.2"}
tracing-log = { path = "../tracing-log", version = "0.1.1", features = ["env_logger"] }
tracing-serde = { path = "../tracing-serde" }
tracing-opentelemetry = { path = "../tracing-opentelemetry" }

# serde example
serde_json = "1.0"

futures = "0.3"
tokio = { version = "0.2.11", features = ["full"] }

# env-logger example
env_logger = "0.6"

# tower examples
tower = "0.3"
tower-util = "0.3.1"
tower-make = "0.3"
http = "0.2"
hyper = "0.13.2"
rand = "0.7"
bytes = "0.5"
clap = "2.33"

# sloggish example
ansi_term = "0.11"
humantime = "1.2"
log = "0.4"

# infero example
inferno = "0.9.4"
eyre = "0.3.5"
indenter = "0.1.3"
tempdir = "0.3.7"

# opentelemetry example
opentelemetry = "0.4"
opentelemetry-jaeger = "0.3"
