[package]
name = "tracing-core"
# When releasing to crates.io:
# - Remove path dependencies
# - Update html_root_url.
# - Update doc url
#   - Cargo.toml
#   - README.md
# - Update CHANGELOG.md.
# - Create "v0.1.x" git tag.
version = "0.1.0"
authors = ["Tokio Contributors <team@tokio.rs>"]
license = "MIT"
repository = "https://github.com/tokio-rs/tracing"
homepage = "https://tokio.rs"
documentation = "https://docs.rs/tracing-core/0.1.0/tracing_core"
description = """
Core primitives for application-level tracing.
"""
categories = ["development-tools::debugging"]
keywords = ["logging", "tracing"]

[dependencies]
lazy_static = "1.0.0"
