[package]
name = "tracing-subscriber"
version = "0.0.1-alpha.1"
authors = ["Eliza Weisman <eliza@buoyant.io>", "Tokio Contributors <team@tokio.rs>"]
edition = "2018"
license = "MIT"
readme = "README.md"
documentation = "https://docs.rs/tracing-subscriber/0.0.1-alpha.1/tracing-subscriber"
description = """
Utilities for implementing and composing `tracing` subscribers.
"""
categories = [
    "development-tools::debugging",
    "development-tools::profiling",
    "asynchronous",
]
keywords = ["logging", "tracing", "metrics", "subscriber"]

[dependencies]
tracing-core = "0.1.2"

[dev-dependencies]
tracing = "0.1"

[badges]
azure-devops = { project = "tracing/tracing", pipeline = "tokio-rs.tracing", build = "1" }
maintenance = { status = "experimental" }
